connector:
  # Server address to bind to.
  bind: 0.0.0.0

  # Application port
  port: 7001

  # Path to compute definitions
  service_file: ./services.py

docker:
  # URL of the Docker server
  url: unix://var/run/docker.sock
